/**
 * Emojis para as categorias de comandos
 * A ordem das chaves define a ordem de apresentação das categorias
 */
const CATEGORY_EMOJIS = {
	geral: "📃",
	grupo: "👥",
	midia: "📱",
	ia: "🤖",
	utilidades: "🛠️",
	jogos: "🎮",
	áudio: "🔈",
	diversao: "🧸",
	zoeira: "🤪",
	downloaders: "📤",
	imagens: "📷",
	tts: "🗣",
	busca: "🔎",
	cultura: "🍿",
	listas: "📜",
	saude: "🥗",
	general: "🖨️",
	info: "ℹ️",
	arquivos: "📂",
	resto: "❓"
};

/**
 * Ordem personalizada para comandos por nome
 * Os comandos não listados aparecem depois na ordem original
 */
const COMMAND_ORDER = [
	"retrospectiva",
	"cmd",
	"ajuda",
	"cmd-grupo",
	"cmd-gerenciamento",
	"cmd-g",
	"avisos",
	"status",
	"doar",
	"convite",
	"grupao",
	"codigo",
	"atencao",
	"ignorar",
	"apagar",
	"apelido",
	"faladores",
	"faladores-limpeza",
	"faladores-reset",
	"clima",
	"news",
	"stt",
	"traduzir",
	"lembretes",
	"lembrar",
	"l-cancelar",
	"comida",
	"comida-info",
	"comida-lista",
	"f",
	"fig",
	"figurinha",
	"s",
	"sticker",
	"sqi",
	"sbg, stickerbg",

	"removebg",
	"distort",
	"neon",
	"oil",
	"pixelate",
	"sketch",
	"ai",
	"imagine",
	"resumo",
	"interagir",
	"yt",
	"sr",
	"ragnavena",
	"roletarussa",
	"roletaranking",
	"roleta-ranking",
	"roleta-tempo",
	"roleta-reset",
	"pescar",
	"pesca-iscas",
	"pesca-ranking",
	"pescados",
	"meus-pescados",
	"pesca-info",
	"pesca-lendas",
	"pesca-reset",
	"sequencia",
	"seq",
	"sequencia-ranking",
	"pinto",
	"pinto-ranking",
	"pinto-reset",
	"slots",
	"slots-premios",
	"tarot",
	"anonimo",
	"roll",
	"d10",
	"lol",
	"lol-build",
	"valorant",
	"wr",
	"wr-build",
	"anime",
	"imdb",
	"volume",
	"getaudio",
	"getvoice",
	"tts",
	"tts-mulher",
	"tts-homem",
	"buscar",
	"buscar-img",
	"gif",
	"wiki",
	"lastfm",
	"listas",
	"lc",
	"lct",
	"ld",
	"le",
	"ls",
	"lt",
	"lr",
	"pastas",
	"p-enviar",
	"p-criar",
	"p-baixar",
	"p-excluir",
	"manage",
	"painel",
	"info",
	"setName",
	"setPrefixo",
	"addCmd",
	"addCmdReply",
	"delCmd",
	"cmd-setAdm",
	"cmd-disable",
	"cmd-enable",
	"cmd-react",
	"cmd-startReact",
	"cmd-setDias",
	"cmd-setHoras",
	"variaveis",
	"setBemvindo",
	"setDespedida",
	"setApelido",
	"ignorar",
	"mute",
	"pausar",
	"autoStt",
	"notificar-grupoFechado",
	"notificar-grupoAberto",
	"filtro-palavra",
	"filtro-links",
	"filtro-nsfw",
	"filtro-pessoa",
	"advertir",
	"advertencias",
	"limpar-advertencias",
	"interagir",
	"interagir-cd",
	"interagir-chance",
	"customAdmin",
	"twitch-canal",
	"twitch-mudarTitulo",
	"twitch-usarIA",
	"twitch-titulo-on",
	"twitch-titulo-off",
	"twitch-midia-on",
	"twitch-midia-off",
	"kick-canal",
	"kick-mudarTitulo",
	"kick-usarIA",
	"kick-titulo-on",
	"kick-titulo-off",
	"kick-midia-on",
	"kick-midia-off",
	"youtube-canal",
	"youtube-mudarTitulo",
	"youtube-usarIA",
	"youtube-titulo-on",
	"youtube-titulo-off",
	"youtube-midia-on",
	"youtube-midia-off"
];

module.exports = { COMMAND_ORDER, CATEGORY_EMOJIS };
